version: '3.3'
services:
  frontend:
    image: nentron/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    depends_on:
      - frontend
  web:
    image: nentron/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "
      python manage.py migrate && 
      python manage.py collectstatic --noinput &&
      python manage.py loaddata &&
      gunicorn Foodreact_api.wsgi:application --bind 0:8000"
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend
volumes:
  static_value:
  media_value: