@token = token 057d4809698987d4a60a35d12399380d4e8ce282

POST http://127.0.0.1:8000/auth/token/login/
Content-Type: application/json

{
    "email": "test_user@mail.ru",
    "password": "Blocks_user32"
}

###
POST http://127.0.0.1:8000/token/login/ 
Content-Type: application/json

{
    "email": "test_user@mail.ru",
    "password": "Blocks_user32"
}


###
POST http://127.0.0.1:8000/users/set_password/
Content-Type: application/json
Authorization: {{token}}

{
    "current_password": "Blocks_user32",
    "new_password": "asdf1235464awe"
}

###
POST http://127.0.0.1:8000/auth/token/logout/
Content-Type: application/json
Authorization: {{token}}


###
GET http://127.0.0.1:8000/ingredients?