@token = token 6bb57b3dc75250814617c00116d8c72345175a85

POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
    "email": "test@mail.ru",
    "password": "Blocks_user32"
}

###
POST http://127.0.0.1:8000/auth/token/login/ 
Content-Type: application/json

{
    "email": "test_user@mail.ru",
    "password": "Blocks_user32"
}


###
POST http://127.0.0.1:8000/users/set_password/
Content-Type: application/json
Authorization: {{token}}

{
    "current_password": "Blocks_user32",
    "new_password": "asdf1235464awe"
}

###
POST http://127.0.0.1:8000/auth/token/logout/
Content-Type: application/json
Authorization: {{token}}


###
POST http://127.0.0.1:8000/reciepes/
Content-Type: application/json
Authorization: {{token}}

{
      "ingredients": [
    {
      "id": 450,
      "amount": 25
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "test",
  "text": "test_text",
  "cooking_time": 5
}


###
POST http://127.0.0.1:8000/recipes/
Content-Type: application/json
Authorization: {{token}}

{
      "ingredients": [
    {
      "id": 580,
      "amount": 5
    },
    {
      "id": 325,
      "amount": 42
    },
    {
      "id": 200,
      "amount": 42
    }
  ],
  "tags": [
    3
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "testadfasdf",
  "text": "test_reciept_try",
  "cooking_time": 6
}

###
GET http://127.0.0.1:8000/users/
Content-Type: application/json
Authorization: {{token}}

###
GET http://127.0.0.1:8000/recipes?is_in_shopping_cart=True
Content-Type: application/json
Authorization: {{token}}