@token = token c8f4ab0a7ac0882af3c9b4005283bbcd1bb7c93f

POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "email": "test_user@mail.ru",
    "password": "Blocks_user32"
}

###
POST http://127.0.0.1:8000/token/login/ 
Content-Type: application/json

{
    "email": "test_user@mail.ru",
    "password": "Blocks_user32"
}


###
GET http://127.0.0.1:8000/users/me/
Content-Type: application/json
Authorization: {{token}}

###
POST http://127.0.0.1:8000/logout/
Content-Type: application/json
Authorization: {{token}}