# Generated by Django 3.2.16 on 2023-01-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='cooking_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='image',
            field=models.ImageField(upload_to='reciepes/images/'),
        ),
    ]
