# Generated by Django 3.2.16 on 2023-01-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciept.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='RecieptIngredientCook',
        ),
        migrations.AlterField(
            model_name='reciept',
            name='ingredients',
            field=models.ManyToManyField(to='reciept.IngredientAmount'),
        ),
    ]
