# Generated by Django 3.2.16 on 2023-01-23 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reciept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercart', to=settings.AUTH_USER_MODEL)),
                ('reciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciept_to_cart', to='reciept.reciept')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteReciepes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_favorite', to=settings.AUTH_USER_MODEL)),
                ('reciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciept_to_favorite', to='reciept.reciept')),
            ],
        ),
    ]
