# Generated by Django 3.2.16 on 2023-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0002_auto_20230112_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('color', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reciept',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reciept',
            name='tags',
            field=models.ManyToManyField(to='reciept.Tag'),
        ),
    ]
