# Generated by Django 3.2.16 on 2023-01-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciept', '0003_auto_20230112_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurment_unit',
            new_name='measurement_unit',
        ),
    ]
