name: Foodgram-project-tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-isort
    - name: Run tests
      run: |
        python -m flake8

  build_and_push_to_DockerHub:
    name: Push docker image to docker
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Check out Rep
      uses: actions/checkout@v3
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.DOCK_PASSWORD }}
    - name: Push to Docker hud 
      uses: docker/build-push-action@v3
      with:
        context: ./backend/Foodreact_api
        push: true
        tags: nentron/foodgram

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_dockerHub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          sudo systemctl stop nginx
          sudo docker-compose stop
          sudo docker-compose rm web
          sudo docker-compose up -d --build
